### PR TITLE
Update FormField.vue

### PR DESCRIPTION
**Pull request by XGhozt**

### CODE REVIEW

**Review by bucksterbuck — COMMENTED** [review]
Has this been merged yet?

**Comment by XGhozt** [comment]
No I don't know how to merge two pull requests and I need to just make another one and compile all the assets correctly. Might as well just close these. If I get a chance I'll do it.

**Comment by bucksterbuck** [comment]
I can do it I just don’t know how to operate github to do it 😂

**Comment by XGhozt** [comment]
@bucksterbuck -- same....

**Pull request closed without merging**
